/*
CAPIF_Events_API

API for event subscription management.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package CAPIF_Events_API

import (
	"encoding/json"
)

// AccessControlPolicyList Represents the access control policy list for a published service API.
type AccessControlPolicyList struct {
	// Policy of each API invoker.
	ApiInvokerPolicies []ApiInvokerPolicy `json:"apiInvokerPolicies,omitempty"`
}

// NewAccessControlPolicyList instantiates a new AccessControlPolicyList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccessControlPolicyList() *AccessControlPolicyList {
	this := AccessControlPolicyList{}
	return &this
}

// NewAccessControlPolicyListWithDefaults instantiates a new AccessControlPolicyList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccessControlPolicyListWithDefaults() *AccessControlPolicyList {
	this := AccessControlPolicyList{}
	return &this
}

// GetApiInvokerPolicies returns the ApiInvokerPolicies field value if set, zero value otherwise.
func (o *AccessControlPolicyList) GetApiInvokerPolicies() []ApiInvokerPolicy {
	if o == nil || isNil(o.ApiInvokerPolicies) {
		var ret []ApiInvokerPolicy
		return ret
	}
	return o.ApiInvokerPolicies
}

// GetApiInvokerPoliciesOk returns a tuple with the ApiInvokerPolicies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccessControlPolicyList) GetApiInvokerPoliciesOk() ([]ApiInvokerPolicy, bool) {
	if o == nil || isNil(o.ApiInvokerPolicies) {
    return nil, false
	}
	return o.ApiInvokerPolicies, true
}

// HasApiInvokerPolicies returns a boolean if a field has been set.
func (o *AccessControlPolicyList) HasApiInvokerPolicies() bool {
	if o != nil && !isNil(o.ApiInvokerPolicies) {
		return true
	}

	return false
}

// SetApiInvokerPolicies gets a reference to the given []ApiInvokerPolicy and assigns it to the ApiInvokerPolicies field.
func (o *AccessControlPolicyList) SetApiInvokerPolicies(v []ApiInvokerPolicy) {
	o.ApiInvokerPolicies = v
}

func (o AccessControlPolicyList) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ApiInvokerPolicies) {
		toSerialize["apiInvokerPolicies"] = o.ApiInvokerPolicies
	}
	return json.Marshal(toSerialize)
}

type NullableAccessControlPolicyList struct {
	value *AccessControlPolicyList
	isSet bool
}

func (v NullableAccessControlPolicyList) Get() *AccessControlPolicyList {
	return v.value
}

func (v *NullableAccessControlPolicyList) Set(val *AccessControlPolicyList) {
	v.value = val
	v.isSet = true
}

func (v NullableAccessControlPolicyList) IsSet() bool {
	return v.isSet
}

func (v *NullableAccessControlPolicyList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccessControlPolicyList(val *AccessControlPolicyList) *NullableAccessControlPolicyList {
	return &NullableAccessControlPolicyList{value: val, isSet: true}
}

func (v NullableAccessControlPolicyList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccessControlPolicyList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


