/*
Ntsctsf_QoSandTSCAssistance Service API

Testing EventsSubscriptionDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Ntsctsf_QoSandTSCAssistance

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Ntsctsf_QoSandTSCAssistance_EventsSubscriptionDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test EventsSubscriptionDocumentApiService DeleteEventsSubsc", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var appSessionId string

        resp, httpRes, err := apiClient.EventsSubscriptionDocumentApi.DeleteEventsSubsc(context.Background(), appSessionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test EventsSubscriptionDocumentApiService PutEventsSubsc", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var appSessionId string

        resp, httpRes, err := apiClient.EventsSubscriptionDocumentApi.PutEventsSubsc(context.Background(), appSessionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
