/*
Nbsf_Management

Testing PCFBindingsCollectionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nbsf_Management

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Nbsf_Management_PCFBindingsCollectionApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test PCFBindingsCollectionApiService CreatePCFBinding", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.PCFBindingsCollectionApi.CreatePCFBinding(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test PCFBindingsCollectionApiService GetPCFBindings", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.PCFBindingsCollectionApi.GetPCFBindings(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
