/*
Npcf_MBSPolicyAuthorization API

Testing IndividualMBSApplicationSessionContextDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Npcf_MBSPolicyAuthorization

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Npcf_MBSPolicyAuthorization_IndividualMBSApplicationSessionContextDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualMBSApplicationSessionContextDocumentApiService DeleteMBSAppSessionCtxt", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var contextId string

        resp, httpRes, err := apiClient.IndividualMBSApplicationSessionContextDocumentApi.DeleteMBSAppSessionCtxt(context.Background(), contextId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualMBSApplicationSessionContextDocumentApiService GetMBSAppSessionCtxt", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var contextId string

        resp, httpRes, err := apiClient.IndividualMBSApplicationSessionContextDocumentApi.GetMBSAppSessionCtxt(context.Background(), contextId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualMBSApplicationSessionContextDocumentApiService ModifyMBSAppSessionCtxt", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var contextId string

        resp, httpRes, err := apiClient.IndividualMBSApplicationSessionContextDocumentApi.ModifyMBSAppSessionCtxt(context.Background(), contextId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
