/*
3gpp-mbs-ud-ingest

API for MBS User Data Ingest Session.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_MBSUserDataIngestSession

import (
	"encoding/json"
)

// MbStfIngestAddr MBSTF Ingest Addresses
type MbStfIngestAddr struct {
	AfEgressTunAddr *TunnelAddress `json:"afEgressTunAddr,omitempty"`
	MbStfIngressTunAddr *TunnelAddress `json:"mbStfIngressTunAddr,omitempty"`
	AfSsm *ExtSsm `json:"afSsm,omitempty"`
	MbStfListenAddr *TunnelAddress `json:"mbStfListenAddr,omitempty"`
}

// NewMbStfIngestAddr instantiates a new MbStfIngestAddr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMbStfIngestAddr() *MbStfIngestAddr {
	this := MbStfIngestAddr{}
	return &this
}

// NewMbStfIngestAddrWithDefaults instantiates a new MbStfIngestAddr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMbStfIngestAddrWithDefaults() *MbStfIngestAddr {
	this := MbStfIngestAddr{}
	return &this
}

// GetAfEgressTunAddr returns the AfEgressTunAddr field value if set, zero value otherwise.
func (o *MbStfIngestAddr) GetAfEgressTunAddr() TunnelAddress {
	if o == nil || isNil(o.AfEgressTunAddr) {
		var ret TunnelAddress
		return ret
	}
	return *o.AfEgressTunAddr
}

// GetAfEgressTunAddrOk returns a tuple with the AfEgressTunAddr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MbStfIngestAddr) GetAfEgressTunAddrOk() (*TunnelAddress, bool) {
	if o == nil || isNil(o.AfEgressTunAddr) {
    return nil, false
	}
	return o.AfEgressTunAddr, true
}

// HasAfEgressTunAddr returns a boolean if a field has been set.
func (o *MbStfIngestAddr) HasAfEgressTunAddr() bool {
	if o != nil && !isNil(o.AfEgressTunAddr) {
		return true
	}

	return false
}

// SetAfEgressTunAddr gets a reference to the given TunnelAddress and assigns it to the AfEgressTunAddr field.
func (o *MbStfIngestAddr) SetAfEgressTunAddr(v TunnelAddress) {
	o.AfEgressTunAddr = &v
}

// GetMbStfIngressTunAddr returns the MbStfIngressTunAddr field value if set, zero value otherwise.
func (o *MbStfIngestAddr) GetMbStfIngressTunAddr() TunnelAddress {
	if o == nil || isNil(o.MbStfIngressTunAddr) {
		var ret TunnelAddress
		return ret
	}
	return *o.MbStfIngressTunAddr
}

// GetMbStfIngressTunAddrOk returns a tuple with the MbStfIngressTunAddr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MbStfIngestAddr) GetMbStfIngressTunAddrOk() (*TunnelAddress, bool) {
	if o == nil || isNil(o.MbStfIngressTunAddr) {
    return nil, false
	}
	return o.MbStfIngressTunAddr, true
}

// HasMbStfIngressTunAddr returns a boolean if a field has been set.
func (o *MbStfIngestAddr) HasMbStfIngressTunAddr() bool {
	if o != nil && !isNil(o.MbStfIngressTunAddr) {
		return true
	}

	return false
}

// SetMbStfIngressTunAddr gets a reference to the given TunnelAddress and assigns it to the MbStfIngressTunAddr field.
func (o *MbStfIngestAddr) SetMbStfIngressTunAddr(v TunnelAddress) {
	o.MbStfIngressTunAddr = &v
}

// GetAfSsm returns the AfSsm field value if set, zero value otherwise.
func (o *MbStfIngestAddr) GetAfSsm() ExtSsm {
	if o == nil || isNil(o.AfSsm) {
		var ret ExtSsm
		return ret
	}
	return *o.AfSsm
}

// GetAfSsmOk returns a tuple with the AfSsm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MbStfIngestAddr) GetAfSsmOk() (*ExtSsm, bool) {
	if o == nil || isNil(o.AfSsm) {
    return nil, false
	}
	return o.AfSsm, true
}

// HasAfSsm returns a boolean if a field has been set.
func (o *MbStfIngestAddr) HasAfSsm() bool {
	if o != nil && !isNil(o.AfSsm) {
		return true
	}

	return false
}

// SetAfSsm gets a reference to the given ExtSsm and assigns it to the AfSsm field.
func (o *MbStfIngestAddr) SetAfSsm(v ExtSsm) {
	o.AfSsm = &v
}

// GetMbStfListenAddr returns the MbStfListenAddr field value if set, zero value otherwise.
func (o *MbStfIngestAddr) GetMbStfListenAddr() TunnelAddress {
	if o == nil || isNil(o.MbStfListenAddr) {
		var ret TunnelAddress
		return ret
	}
	return *o.MbStfListenAddr
}

// GetMbStfListenAddrOk returns a tuple with the MbStfListenAddr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MbStfIngestAddr) GetMbStfListenAddrOk() (*TunnelAddress, bool) {
	if o == nil || isNil(o.MbStfListenAddr) {
    return nil, false
	}
	return o.MbStfListenAddr, true
}

// HasMbStfListenAddr returns a boolean if a field has been set.
func (o *MbStfIngestAddr) HasMbStfListenAddr() bool {
	if o != nil && !isNil(o.MbStfListenAddr) {
		return true
	}

	return false
}

// SetMbStfListenAddr gets a reference to the given TunnelAddress and assigns it to the MbStfListenAddr field.
func (o *MbStfIngestAddr) SetMbStfListenAddr(v TunnelAddress) {
	o.MbStfListenAddr = &v
}

func (o MbStfIngestAddr) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.AfEgressTunAddr) {
		toSerialize["afEgressTunAddr"] = o.AfEgressTunAddr
	}
	if !isNil(o.MbStfIngressTunAddr) {
		toSerialize["mbStfIngressTunAddr"] = o.MbStfIngressTunAddr
	}
	if !isNil(o.AfSsm) {
		toSerialize["afSsm"] = o.AfSsm
	}
	if !isNil(o.MbStfListenAddr) {
		toSerialize["mbStfListenAddr"] = o.MbStfListenAddr
	}
	return json.Marshal(toSerialize)
}

type NullableMbStfIngestAddr struct {
	value *MbStfIngestAddr
	isSet bool
}

func (v NullableMbStfIngestAddr) Get() *MbStfIngestAddr {
	return v.value
}

func (v *NullableMbStfIngestAddr) Set(val *MbStfIngestAddr) {
	v.value = val
	v.isSet = true
}

func (v NullableMbStfIngestAddr) IsSet() bool {
	return v.isSet
}

func (v *NullableMbStfIngestAddr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMbStfIngestAddr(val *MbStfIngestAddr) *NullableMbStfIngestAddr {
	return &NullableMbStfIngestAddr{value: val, isSet: true}
}

func (v NullableMbStfIngestAddr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMbStfIngestAddr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


