/*
3gpp-asti

Testing ASTIConfigurationsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ASTI

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_ASTI_ASTIConfigurationsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test ASTIConfigurationsApiService CreateNewConfiguration", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var afId string

        resp, httpRes, err := apiClient.ASTIConfigurationsApi.CreateNewConfiguration(context.Background(), afId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ASTIConfigurationsApiService ReadAllConfigurations", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var afId string

        resp, httpRes, err := apiClient.ASTIConfigurationsApi.ReadAllConfigurations(context.Background(), afId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test ASTIConfigurationsApiService RetrieveStatusofConfiguration", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var afId string

        resp, httpRes, err := apiClient.ASTIConfigurationsApi.RetrieveStatusofConfiguration(context.Background(), afId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
