/*
3gpp-device-triggering

Testing DeviceTriggeringAPITransactionsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package DeviceTriggering

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_DeviceTriggering_DeviceTriggeringAPITransactionsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test DeviceTriggeringAPITransactionsApiService CreateDeviceTriggeringTransaction", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var scsAsId string

        resp, httpRes, err := apiClient.DeviceTriggeringAPITransactionsApi.CreateDeviceTriggeringTransaction(context.Background(), scsAsId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
