/*
Nnwdaf_MLModelProvision

Testing IndividualNWDAFMLModelProvisionSubscriptionDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nnwdaf_MLModelProvision

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Nnwdaf_MLModelProvision_IndividualNWDAFMLModelProvisionSubscriptionDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualNWDAFMLModelProvisionSubscriptionDocumentApiService DeleteNWDAFMLModelProvisionSubcription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualNWDAFMLModelProvisionSubscriptionDocumentApi.DeleteNWDAFMLModelProvisionSubcription(context.Background(), subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualNWDAFMLModelProvisionSubscriptionDocumentApiService UpdateNWDAFMLModelProvisionSubcription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualNWDAFMLModelProvisionSubscriptionDocumentApi.UpdateNWDAFMLModelProvisionSubcription(context.Background(), subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
