/*
GMDviaMBMSbyMB2

Testing IndividualTMGIAllocationOperationApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package GMDviaMBMSbyMB2

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_GMDviaMBMSbyMB2_IndividualTMGIAllocationOperationApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualTMGIAllocationOperationApiService DeleteTMGIAllocation", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var scsAsId string
        var tmgi string

        resp, httpRes, err := apiClient.IndividualTMGIAllocationOperationApi.DeleteTMGIAllocation(context.Background(), scsAsId, tmgi).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualTMGIAllocationOperationApiService FetchIndTMGIAllocation", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var scsAsId string
        var tmgi string

        resp, httpRes, err := apiClient.IndividualTMGIAllocationOperationApi.FetchIndTMGIAllocation(context.Background(), scsAsId, tmgi).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualTMGIAllocationOperationApiService ModifyIndTMGIAllocation", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var scsAsId string
        var tmgi string

        resp, httpRes, err := apiClient.IndividualTMGIAllocationOperationApi.ModifyIndTMGIAllocation(context.Background(), scsAsId, tmgi).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualTMGIAllocationOperationApiService UpdateIndTMGIAllocation", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var scsAsId string
        var tmgi string

        resp, httpRes, err := apiClient.IndividualTMGIAllocationOperationApi.UpdateIndTMGIAllocation(context.Background(), scsAsId, tmgi).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
