/*
Nspaf_SecuredPacket

Testing SecuredPacketGenerationCustomOperationApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nspaf_SecuredPacket

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Nspaf_SecuredPacket_SecuredPacketGenerationCustomOperationApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test SecuredPacketGenerationCustomOperationApiService ProvideSecuredPacket", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var supi string

        resp, httpRes, err := apiClient.SecuredPacketGenerationCustomOperationApi.ProvideSecuredPacket(context.Background(), supi).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
