/*
M1_ProvisioningSessions

Testing DefaultApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package M1_ProvisioningSessions

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_M1_ProvisioningSessions_DefaultApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test DefaultApiService CreateProvisioningSession", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.DefaultApi.CreateProvisioningSession(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test DefaultApiService DestroyProvisioningSession", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var provisioningSessionId string

        resp, httpRes, err := apiClient.DefaultApi.DestroyProvisioningSession(context.Background(), provisioningSessionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test DefaultApiService GetProvisioningSessionById", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var provisioningSessionId string

        resp, httpRes, err := apiClient.DefaultApi.GetProvisioningSessionById(context.Background(), provisioningSessionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
