/*
5G-EIR Equipment Identity Check

Testing EquipmentStatusDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package N5g-eir_EquipmentIdentityCheck

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_N5g-eir_EquipmentIdentityCheck_EquipmentStatusDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test EquipmentStatusDocumentApiService GetEquipmentStatus", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.EquipmentStatusDocumentApi.GetEquipmentStatus(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
