/*
3gpp-service-parameter

Testing IndividualServiceParameterSubscriptionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ServiceParameter

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_ServiceParameter_IndividualServiceParameterSubscriptionApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualServiceParameterSubscriptionApiService DeleteAnSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var afId string
        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualServiceParameterSubscriptionApi.DeleteAnSubscription(context.Background(), afId, subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualServiceParameterSubscriptionApiService FullyUpdateAnSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var afId string
        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualServiceParameterSubscriptionApi.FullyUpdateAnSubscription(context.Background(), afId, subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualServiceParameterSubscriptionApiService PartialUpdateAnSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var afId string
        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualServiceParameterSubscriptionApi.PartialUpdateAnSubscription(context.Background(), afId, subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualServiceParameterSubscriptionApiService ReadAnSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var afId string
        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualServiceParameterSubscriptionApi.ReadAnSubscription(context.Background(), afId, subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
