/*
Nhss_imsSDM

Nhss Subscriber Data Management Service for IMS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.1.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Nhss_imsSDM

import (
	"encoding/json"
)

// DsaiTagStatus DSAI tag status (DSAI tag and activation state)
type DsaiTagStatus struct {
	DsaiTag string `json:"dsaiTag"`
	DsaiState ActivationState `json:"dsaiState"`
}

// NewDsaiTagStatus instantiates a new DsaiTagStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDsaiTagStatus(dsaiTag string, dsaiState ActivationState) *DsaiTagStatus {
	this := DsaiTagStatus{}
	this.DsaiTag = dsaiTag
	this.DsaiState = dsaiState
	return &this
}

// NewDsaiTagStatusWithDefaults instantiates a new DsaiTagStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDsaiTagStatusWithDefaults() *DsaiTagStatus {
	this := DsaiTagStatus{}
	return &this
}

// GetDsaiTag returns the DsaiTag field value
func (o *DsaiTagStatus) GetDsaiTag() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DsaiTag
}

// GetDsaiTagOk returns a tuple with the DsaiTag field value
// and a boolean to check if the value has been set.
func (o *DsaiTagStatus) GetDsaiTagOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.DsaiTag, true
}

// SetDsaiTag sets field value
func (o *DsaiTagStatus) SetDsaiTag(v string) {
	o.DsaiTag = v
}

// GetDsaiState returns the DsaiState field value
func (o *DsaiTagStatus) GetDsaiState() ActivationState {
	if o == nil {
		var ret ActivationState
		return ret
	}

	return o.DsaiState
}

// GetDsaiStateOk returns a tuple with the DsaiState field value
// and a boolean to check if the value has been set.
func (o *DsaiTagStatus) GetDsaiStateOk() (*ActivationState, bool) {
	if o == nil {
    return nil, false
	}
	return &o.DsaiState, true
}

// SetDsaiState sets field value
func (o *DsaiTagStatus) SetDsaiState(v ActivationState) {
	o.DsaiState = v
}

func (o DsaiTagStatus) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["dsaiTag"] = o.DsaiTag
	}
	if true {
		toSerialize["dsaiState"] = o.DsaiState
	}
	return json.Marshal(toSerialize)
}

type NullableDsaiTagStatus struct {
	value *DsaiTagStatus
	isSet bool
}

func (v NullableDsaiTagStatus) Get() *DsaiTagStatus {
	return v.value
}

func (v *NullableDsaiTagStatus) Set(val *DsaiTagStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableDsaiTagStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableDsaiTagStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDsaiTagStatus(val *DsaiTagStatus) *NullableDsaiTagStatus {
	return &NullableDsaiTagStatus{value: val, isSet: true}
}

func (v NullableDsaiTagStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDsaiTagStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


