/*
Eecs_ServiceProvisioning

Testing IndividualServiceProvisioningSubscriptionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Eecs_ServiceProvisioning

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Eecs_ServiceProvisioning_IndividualServiceProvisioningSubscriptionApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualServiceProvisioningSubscriptionApiService SubscriptionsSubscriptionIdDelete", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualServiceProvisioningSubscriptionApi.SubscriptionsSubscriptionIdDelete(context.Background(), subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualServiceProvisioningSubscriptionApiService SubscriptionsSubscriptionIdPatch", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualServiceProvisioningSubscriptionApi.SubscriptionsSubscriptionIdPatch(context.Background(), subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualServiceProvisioningSubscriptionApiService SubscriptionsSubscriptionIdPut", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualServiceProvisioningSubscriptionApi.SubscriptionsSubscriptionIdPut(context.Background(), subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
