/*
Namf_MT

Testing UeContextsCollectionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Namf_MT

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Namf_MT_UeContextsCollectionApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test UeContextsCollectionApiService EnableGroupReachability", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.UeContextsCollectionApi.EnableGroupReachability(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
