/*
VAE_V2VConfigRequirement

Testing IndividualV2VConfigurationDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package VAE_V2VConfigRequirement

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_VAE_V2VConfigRequirement_IndividualV2VConfigurationDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualV2VConfigurationDocumentApiService DeleteV2VConfiguration", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var configurationId string

        resp, httpRes, err := apiClient.IndividualV2VConfigurationDocumentApi.DeleteV2VConfiguration(context.Background(), configurationId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualV2VConfigurationDocumentApiService ReadV2VConfiguration", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var configurationId string

        resp, httpRes, err := apiClient.IndividualV2VConfigurationDocumentApi.ReadV2VConfiguration(context.Background(), configurationId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
