/*
3gpp-data-reporting

Testing DataReportingSessionsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package DataReporting

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_DataReporting_DataReportingSessionsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test DataReportingSessionsApiService CreateDataRepSession", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.DataReportingSessionsApi.CreateDataRepSession(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
