/*
Nmbsmf-MBSSession

Testing SubscriptionsCollectionForMBSSessionsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nmbsmf_MBSSession

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Nmbsmf_MBSSession_SubscriptionsCollectionForMBSSessionsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test SubscriptionsCollectionForMBSSessionsApiService StatusSubscribe", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.SubscriptionsCollectionForMBSSessionsApi.StatusSubscribe(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
