/*
Unified Data Repository Service API file for policy data

Testing IndividualBdtDataDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Policy_Data

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Policy_Data_IndividualBdtDataDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualBdtDataDocumentApiService CreateIndividualBdtData", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var bdtReferenceId string

        resp, httpRes, err := apiClient.IndividualBdtDataDocumentApi.CreateIndividualBdtData(context.Background(), bdtReferenceId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualBdtDataDocumentApiService DeleteIndividualBdtData", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var bdtReferenceId string

        resp, httpRes, err := apiClient.IndividualBdtDataDocumentApi.DeleteIndividualBdtData(context.Background(), bdtReferenceId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualBdtDataDocumentApiService ReadIndividualBdtData", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var bdtReferenceId string

        resp, httpRes, err := apiClient.IndividualBdtDataDocumentApi.ReadIndividualBdtData(context.Background(), bdtReferenceId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualBdtDataDocumentApiService UpdateIndividualBdtData", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var bdtReferenceId string

        resp, httpRes, err := apiClient.IndividualBdtDataDocumentApi.UpdateIndividualBdtData(context.Background(), bdtReferenceId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
