/*
Unified Data Repository Service API file for policy data

Testing OperatorSpecificDataDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Policy_Data

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Policy_Data_OperatorSpecificDataDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test OperatorSpecificDataDocumentApiService DeleteOperatorSpecificData", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var ueId string

        resp, httpRes, err := apiClient.OperatorSpecificDataDocumentApi.DeleteOperatorSpecificData(context.Background(), ueId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test OperatorSpecificDataDocumentApiService ReadOperatorSpecificData", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var ueId string

        resp, httpRes, err := apiClient.OperatorSpecificDataDocumentApi.ReadOperatorSpecificData(context.Background(), ueId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test OperatorSpecificDataDocumentApiService ReplaceOperatorSpecificData", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var ueId string

        resp, httpRes, err := apiClient.OperatorSpecificDataDocumentApi.ReplaceOperatorSpecificData(context.Background(), ueId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test OperatorSpecificDataDocumentApiService UpdateOperatorSpecificData", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var ueId string

        resp, httpRes, err := apiClient.OperatorSpecificDataDocumentApi.UpdateOperatorSpecificData(context.Background(), ueId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
