/*
Nsmf_PDUSession

Testing IndividualPDUSessionHSMFOrSMFApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nsmf_PDUSession

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Nsmf_PDUSession_IndividualPDUSessionHSMFOrSMFApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualPDUSessionHSMFOrSMFApiService ReleasePduSession", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var pduSessionRef string

        resp, httpRes, err := apiClient.IndividualPDUSessionHSMFOrSMFApi.ReleasePduSession(context.Background(), pduSessionRef).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualPDUSessionHSMFOrSMFApiService RetrievePduSession", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var pduSessionRef string

        resp, httpRes, err := apiClient.IndividualPDUSessionHSMFOrSMFApi.RetrievePduSession(context.Background(), pduSessionRef).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualPDUSessionHSMFOrSMFApiService TransferMoData", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var pduSessionRef string

        resp, httpRes, err := apiClient.IndividualPDUSessionHSMFOrSMFApi.TransferMoData(context.Background(), pduSessionRef).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualPDUSessionHSMFOrSMFApiService UpdatePduSession", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var pduSessionRef string

        resp, httpRes, err := apiClient.IndividualPDUSessionHSMFOrSMFApi.UpdatePduSession(context.Background(), pduSessionRef).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
