/*
Eees Application Context Relocation Service

Testing InitiateACRApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Eees_AppContextRelocation

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Eees_AppContextRelocation_InitiateACRApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test InitiateACRApiService Initiate", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.InitiateACRApi.Initiate(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
