/*
Nudsf_DataRepository

Testing NotificationSubscriptionsCRUDApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nudsf_DataRepository

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Nudsf_DataRepository_NotificationSubscriptionsCRUDApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test NotificationSubscriptionsCRUDApiService GetNotificationSubscriptions", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var realmId string
        var storageId string

        resp, httpRes, err := apiClient.NotificationSubscriptionsCRUDApi.GetNotificationSubscriptions(context.Background(), realmId, storageId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
