/*
Nudsf_DataRepository

Testing NotificationSubscriptionCRUDApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nudsf_DataRepository

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Nudsf_DataRepository_NotificationSubscriptionCRUDApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test NotificationSubscriptionCRUDApiService CreateAndUpdateNotificationSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var realmId string
        var storageId string
        var subscriptionId string

        resp, httpRes, err := apiClient.NotificationSubscriptionCRUDApi.CreateAndUpdateNotificationSubscription(context.Background(), realmId, storageId, subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test NotificationSubscriptionCRUDApiService DeleteNotificationSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var realmId string
        var storageId string
        var subscriptionId string

        resp, httpRes, err := apiClient.NotificationSubscriptionCRUDApi.DeleteNotificationSubscription(context.Background(), realmId, storageId, subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test NotificationSubscriptionCRUDApiService GetNotificationSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var realmId string
        var storageId string
        var subscriptionId string

        resp, httpRes, err := apiClient.NotificationSubscriptionCRUDApi.GetNotificationSubscription(context.Background(), realmId, storageId, subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test NotificationSubscriptionCRUDApiService UpdateNotificationSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var realmId string
        var storageId string
        var subscriptionId string

        resp, httpRes, err := apiClient.NotificationSubscriptionCRUDApi.UpdateNotificationSubscription(context.Background(), realmId, storageId, subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
