/*
Nnef_PFDmanagement Service API

Testing PFDSubscriptionsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nnef_PFDmanagement

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Nnef_PFDmanagement_PFDSubscriptionsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test PFDSubscriptionsApiService NnefPFDmanagementCreateSubscr", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.PFDSubscriptionsApi.NnefPFDmanagementCreateSubscr(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
