/*
Nsoraf_SOR

Testing ProvidingTheReceptionStatusOfTheAcknowledgementOfSteeringOfRoamingInformationReceptionByTheUEApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nsoraf_SOR

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Nsoraf_SOR_ProvidingTheReceptionStatusOfTheAcknowledgementOfSteeringOfRoamingInformationReceptionByTheUEApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test ProvidingTheReceptionStatusOfTheAcknowledgementOfSteeringOfRoamingInformationReceptionByTheUEApiService SorAckInfo", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var supi string

        resp, httpRes, err := apiClient.ProvidingTheReceptionStatusOfTheAcknowledgementOfSteeringOfRoamingInformationReceptionByTheUEApi.SorAckInfo(context.Background(), supi).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
