/*
3gpp-cp-parameter-provisioning

Testing IndividualCPSetProvisioningApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package CpProvisioning

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_CpProvisioning_IndividualCPSetProvisioningApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualCPSetProvisioningApiService DeleteIndCPSetProvisioning", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var scsAsId string
        var subscriptionId string
        var setId string

        resp, httpRes, err := apiClient.IndividualCPSetProvisioningApi.DeleteIndCPSetProvisioning(context.Background(), scsAsId, subscriptionId, setId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualCPSetProvisioningApiService FetchIndCPSetProvisioning", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var scsAsId string
        var subscriptionId string
        var setId string

        resp, httpRes, err := apiClient.IndividualCPSetProvisioningApi.FetchIndCPSetProvisioning(context.Background(), scsAsId, subscriptionId, setId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualCPSetProvisioningApiService UpdateIndCPSetProvisioning", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var scsAsId string
        var subscriptionId string
        var setId string

        resp, httpRes, err := apiClient.IndividualCPSetProvisioningApi.UpdateIndCPSetProvisioning(context.Background(), scsAsId, subscriptionId, setId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
