/*
SS_NetworkResourceMonitoring

Testing UnicastMonitoringSubscriptionsCollectionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package SS_NetworkResourceMonitoring

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_SS_NetworkResourceMonitoring_UnicastMonitoringSubscriptionsCollectionApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test UnicastMonitoringSubscriptionsCollectionApiService SubscribeUnicastMonitoring", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.UnicastMonitoringSubscriptionsCollectionApi.SubscribeUnicastMonitoring(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
