/*
SS_NetworkResourceMonitoring

Testing IndividualUnicastMonitoringSubscriptionDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package SS_NetworkResourceMonitoring

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_SS_NetworkResourceMonitoring_IndividualUnicastMonitoringSubscriptionDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualUnicastMonitoringSubscriptionDocumentApiService ReadUnicastMonitoringSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualUnicastMonitoringSubscriptionDocumentApi.ReadUnicastMonitoringSubscription(context.Background(), subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualUnicastMonitoringSubscriptionDocumentApiService UnsubscribeUnicastMonitoring", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualUnicastMonitoringSubscriptionDocumentApi.UnsubscribeUnicastMonitoring(context.Background(), subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
