/*
Eees_EASDiscovery

Testing EASDiscoverySubscriptionsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Eees_EASDiscovery

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Eees_EASDiscovery_EASDiscoverySubscriptionsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test EASDiscoverySubscriptionsApiService SubscriptionsPost", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.EASDiscoverySubscriptionsApi.SubscriptionsPost(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
