/*
SS_GroupManagement

Testing VALGroupDocumentsCollectionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package SS_GroupManagement

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_SS_GroupManagement_VALGroupDocumentsCollectionApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test VALGroupDocumentsCollectionApiService CreateValGroupDoc", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.VALGroupDocumentsCollectionApi.CreateValGroupDoc(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test VALGroupDocumentsCollectionApiService RetrieveValGroupDocs", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.VALGroupDocumentsCollectionApi.RetrieveValGroupDocs(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
