/*
NR NRM

OAS 3.0.1 specification of the NR NRM © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved.

API version: 17.7.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_NrNrm

import (
	"encoding/json"
)

// DPCIConfigurationFunctionSingleAllOf struct for DPCIConfigurationFunctionSingleAllOf
type DPCIConfigurationFunctionSingleAllOf struct {
	Attributes *DPCIConfigurationFunctionSingleAllOfAttributes `json:"attributes,omitempty"`
}

// NewDPCIConfigurationFunctionSingleAllOf instantiates a new DPCIConfigurationFunctionSingleAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDPCIConfigurationFunctionSingleAllOf() *DPCIConfigurationFunctionSingleAllOf {
	this := DPCIConfigurationFunctionSingleAllOf{}
	return &this
}

// NewDPCIConfigurationFunctionSingleAllOfWithDefaults instantiates a new DPCIConfigurationFunctionSingleAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDPCIConfigurationFunctionSingleAllOfWithDefaults() *DPCIConfigurationFunctionSingleAllOf {
	this := DPCIConfigurationFunctionSingleAllOf{}
	return &this
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *DPCIConfigurationFunctionSingleAllOf) GetAttributes() DPCIConfigurationFunctionSingleAllOfAttributes {
	if o == nil || isNil(o.Attributes) {
		var ret DPCIConfigurationFunctionSingleAllOfAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DPCIConfigurationFunctionSingleAllOf) GetAttributesOk() (*DPCIConfigurationFunctionSingleAllOfAttributes, bool) {
	if o == nil || isNil(o.Attributes) {
    return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *DPCIConfigurationFunctionSingleAllOf) HasAttributes() bool {
	if o != nil && !isNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given DPCIConfigurationFunctionSingleAllOfAttributes and assigns it to the Attributes field.
func (o *DPCIConfigurationFunctionSingleAllOf) SetAttributes(v DPCIConfigurationFunctionSingleAllOfAttributes) {
	o.Attributes = &v
}

func (o DPCIConfigurationFunctionSingleAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	return json.Marshal(toSerialize)
}

type NullableDPCIConfigurationFunctionSingleAllOf struct {
	value *DPCIConfigurationFunctionSingleAllOf
	isSet bool
}

func (v NullableDPCIConfigurationFunctionSingleAllOf) Get() *DPCIConfigurationFunctionSingleAllOf {
	return v.value
}

func (v *NullableDPCIConfigurationFunctionSingleAllOf) Set(val *DPCIConfigurationFunctionSingleAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableDPCIConfigurationFunctionSingleAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableDPCIConfigurationFunctionSingleAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDPCIConfigurationFunctionSingleAllOf(val *DPCIConfigurationFunctionSingleAllOf) *NullableDPCIConfigurationFunctionSingleAllOf {
	return &NullableDPCIConfigurationFunctionSingleAllOf{value: val, isSet: true}
}

func (v NullableDPCIConfigurationFunctionSingleAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDPCIConfigurationFunctionSingleAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


