/*
Npcf_BDTPolicyControl Service API

Testing IndividualBDTPolicyDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Npcf_BDTPolicyControl

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Npcf_BDTPolicyControl_IndividualBDTPolicyDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualBDTPolicyDocumentApiService GetBDTPolicy", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var bdtPolicyId string

        resp, httpRes, err := apiClient.IndividualBDTPolicyDocumentApi.GetBDTPolicy(context.Background(), bdtPolicyId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualBDTPolicyDocumentApiService UpdateBDTPolicy", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var bdtPolicyId string

        resp, httpRes, err := apiClient.IndividualBDTPolicyDocumentApi.UpdateBDTPolicy(context.Background(), bdtPolicyId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
