/*
M1_ContentHostingProvisioning

5GMS AF M1 Content Hosting Provisioning API © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package M1_ContentHostingProvisioning

import (
	"encoding/json"
)

// IngestConfiguration A configuration for content ingest.
type IngestConfiguration struct {
	Path *string `json:"path,omitempty"`
	Pull *bool `json:"pull,omitempty"`
	// String providing an URI formatted according to RFC 3986.
	Protocol *string `json:"protocol,omitempty"`
	// Uniform Resource Locator, comforming with the URI Generic Syntax specified in IETF RFC 3986.
	EntryPoint *string `json:"entryPoint,omitempty"`
}

// NewIngestConfiguration instantiates a new IngestConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIngestConfiguration() *IngestConfiguration {
	this := IngestConfiguration{}
	return &this
}

// NewIngestConfigurationWithDefaults instantiates a new IngestConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIngestConfigurationWithDefaults() *IngestConfiguration {
	this := IngestConfiguration{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *IngestConfiguration) GetPath() string {
	if o == nil || isNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngestConfiguration) GetPathOk() (*string, bool) {
	if o == nil || isNil(o.Path) {
    return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *IngestConfiguration) HasPath() bool {
	if o != nil && !isNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *IngestConfiguration) SetPath(v string) {
	o.Path = &v
}

// GetPull returns the Pull field value if set, zero value otherwise.
func (o *IngestConfiguration) GetPull() bool {
	if o == nil || isNil(o.Pull) {
		var ret bool
		return ret
	}
	return *o.Pull
}

// GetPullOk returns a tuple with the Pull field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngestConfiguration) GetPullOk() (*bool, bool) {
	if o == nil || isNil(o.Pull) {
    return nil, false
	}
	return o.Pull, true
}

// HasPull returns a boolean if a field has been set.
func (o *IngestConfiguration) HasPull() bool {
	if o != nil && !isNil(o.Pull) {
		return true
	}

	return false
}

// SetPull gets a reference to the given bool and assigns it to the Pull field.
func (o *IngestConfiguration) SetPull(v bool) {
	o.Pull = &v
}

// GetProtocol returns the Protocol field value if set, zero value otherwise.
func (o *IngestConfiguration) GetProtocol() string {
	if o == nil || isNil(o.Protocol) {
		var ret string
		return ret
	}
	return *o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngestConfiguration) GetProtocolOk() (*string, bool) {
	if o == nil || isNil(o.Protocol) {
    return nil, false
	}
	return o.Protocol, true
}

// HasProtocol returns a boolean if a field has been set.
func (o *IngestConfiguration) HasProtocol() bool {
	if o != nil && !isNil(o.Protocol) {
		return true
	}

	return false
}

// SetProtocol gets a reference to the given string and assigns it to the Protocol field.
func (o *IngestConfiguration) SetProtocol(v string) {
	o.Protocol = &v
}

// GetEntryPoint returns the EntryPoint field value if set, zero value otherwise.
func (o *IngestConfiguration) GetEntryPoint() string {
	if o == nil || isNil(o.EntryPoint) {
		var ret string
		return ret
	}
	return *o.EntryPoint
}

// GetEntryPointOk returns a tuple with the EntryPoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IngestConfiguration) GetEntryPointOk() (*string, bool) {
	if o == nil || isNil(o.EntryPoint) {
    return nil, false
	}
	return o.EntryPoint, true
}

// HasEntryPoint returns a boolean if a field has been set.
func (o *IngestConfiguration) HasEntryPoint() bool {
	if o != nil && !isNil(o.EntryPoint) {
		return true
	}

	return false
}

// SetEntryPoint gets a reference to the given string and assigns it to the EntryPoint field.
func (o *IngestConfiguration) SetEntryPoint(v string) {
	o.EntryPoint = &v
}

func (o IngestConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !isNil(o.Pull) {
		toSerialize["pull"] = o.Pull
	}
	if !isNil(o.Protocol) {
		toSerialize["protocol"] = o.Protocol
	}
	if !isNil(o.EntryPoint) {
		toSerialize["entryPoint"] = o.EntryPoint
	}
	return json.Marshal(toSerialize)
}

type NullableIngestConfiguration struct {
	value *IngestConfiguration
	isSet bool
}

func (v NullableIngestConfiguration) Get() *IngestConfiguration {
	return v.value
}

func (v *NullableIngestConfiguration) Set(val *IngestConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableIngestConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableIngestConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIngestConfiguration(val *IngestConfiguration) *NullableIngestConfiguration {
	return &NullableIngestConfiguration{value: val, isSet: true}
}

func (v NullableIngestConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIngestConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


