/*
Npanf_ProseKey

Testing ProsekeyRegistrationApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Npanf_ProseKey

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Npanf_ProseKey_ProsekeyRegistrationApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test ProsekeyRegistrationApiService ProseKeyRegistration", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.ProsekeyRegistrationApi.ProseKeyRegistration(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
