/*
CAPIF_API_Invoker_Management_API

Testing DefaultApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package CAPIF_API_Invoker_Management_API

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_CAPIF_API_Invoker_Management_API_DefaultApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test DefaultApiService OnboardedInvokersOnboardingIdDelete", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var onboardingId string

        resp, httpRes, err := apiClient.DefaultApi.OnboardedInvokersOnboardingIdDelete(context.Background(), onboardingId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test DefaultApiService OnboardedInvokersOnboardingIdPut", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var onboardingId string

        resp, httpRes, err := apiClient.DefaultApi.OnboardedInvokersOnboardingIdPut(context.Background(), onboardingId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test DefaultApiService OnboardedInvokersPost", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.DefaultApi.OnboardedInvokersPost(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
