/*
Namf_Location

Testing IndividualUEContextDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Namf_Location

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Namf_Location_IndividualUEContextDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualUEContextDocumentApiService CancelLocation", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var ueContextId string

        resp, httpRes, err := apiClient.IndividualUEContextDocumentApi.CancelLocation(context.Background(), ueContextId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualUEContextDocumentApiService ProvideLocationInfo", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var ueContextId string

        resp, httpRes, err := apiClient.IndividualUEContextDocumentApi.ProvideLocationInfo(context.Background(), ueContextId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualUEContextDocumentApiService ProvidePositioningInfo", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var ueContextId string

        resp, httpRes, err := apiClient.IndividualUEContextDocumentApi.ProvidePositioningInfo(context.Background(), ueContextId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
