/*
3gpp-mbs-session

Testing IndividualMBSSessionSubscriptionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package MBSSession

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_MBSSession_IndividualMBSSessionSubscriptionApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualMBSSessionSubscriptionApiService DeleteIndMBSSessionsSubsc", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualMBSSessionSubscriptionApi.DeleteIndMBSSessionsSubsc(context.Background(), subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualMBSSessionSubscriptionApiService ReadIndMBSSessionsSubsc", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualMBSSessionSubscriptionApi.ReadIndMBSSessionsSubsc(context.Background(), subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
