/*
Unified Data Repository Service API file for subscription data

Testing SMSManagementSubscriptionDataDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Subscription_Data

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Subscription_Data_SMSManagementSubscriptionDataDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test SMSManagementSubscriptionDataDocumentApiService QuerySmsMngData", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var ueId string
        var servingPlmnId string

        resp, httpRes, err := apiClient.SMSManagementSubscriptionDataDocumentApi.QuerySmsMngData(context.Background(), ueId, servingPlmnId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
