/*
Unified Data Repository Service API file for subscription data

Testing ParameterProvisionProfileDataFor5GVNGroupDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Subscription_Data

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Subscription_Data_ParameterProvisionProfileDataFor5GVNGroupDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test ParameterProvisionProfileDataFor5GVNGroupDocumentApiService Query5GVNGroupPPData", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.ParameterProvisionProfileDataFor5GVNGroupDocumentApi.Query5GVNGroupPPData(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
