/*
M5_DynamicPolicies

Testing DefaultApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package M5_DynamicPolicies

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_M5_DynamicPolicies_DefaultApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test DefaultApiService CreateDynamicPolicy", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        resp, httpRes, err := apiClient.DefaultApi.CreateDynamicPolicy(context.Background()).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test DefaultApiService DestroyDynamicPolicy", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var dynamicPolicyId string

        resp, httpRes, err := apiClient.DefaultApi.DestroyDynamicPolicy(context.Background(), dynamicPolicyId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test DefaultApiService PatchDynamicPolicy", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var dynamicPolicyId string

        resp, httpRes, err := apiClient.DefaultApi.PatchDynamicPolicy(context.Background(), dynamicPolicyId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test DefaultApiService RetrieveDynamicPolicy", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var dynamicPolicyId string

        resp, httpRes, err := apiClient.DefaultApi.RetrieveDynamicPolicy(context.Background(), dynamicPolicyId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test DefaultApiService UpdateDynamicPolicy", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var dynamicPolicyId string

        resp, httpRes, err := apiClient.DefaultApi.UpdateDynamicPolicy(context.Background(), dynamicPolicyId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
