/*
3gpp-am-policyauthorization

Testing AMPolicyEventsSubscriptionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package AMPolicyAuthorization

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_AMPolicyAuthorization_AMPolicyEventsSubscriptionApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test AMPolicyEventsSubscriptionApiService DeleteAmEventsSubsc", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var afId string
        var appAmContextId string

        resp, httpRes, err := apiClient.AMPolicyEventsSubscriptionApi.DeleteAmEventsSubsc(context.Background(), afId, appAmContextId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test AMPolicyEventsSubscriptionApiService UpdateAmEventsSubsc", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var afId string
        var appAmContextId string

        resp, httpRes, err := apiClient.AMPolicyEventsSubscriptionApi.UpdateAmEventsSubsc(context.Background(), afId, appAmContextId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
