/*
3gpp-bdt

Testing BDTSubscriptionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package ResourceManagementOfBdt

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_ResourceManagementOfBdt_BDTSubscriptionApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test BDTSubscriptionApiService CreateBDTSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var scsAsId string

        resp, httpRes, err := apiClient.BDTSubscriptionApi.CreateBDTSubscription(context.Background(), scsAsId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test BDTSubscriptionApiService FetchAllActiveBDTSubscriptions", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var scsAsId string

        resp, httpRes, err := apiClient.BDTSubscriptionApi.FetchAllActiveBDTSubscriptions(context.Background(), scsAsId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
