/*
Nudr_DataRepository API OpenAPI file

Testing QueryAMFSubscriptionInfoDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nudr_DR

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Nudr_DR_QueryAMFSubscriptionInfoDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test QueryAMFSubscriptionInfoDocumentApiService GetAmfGroupSubscriptions", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var ueGroupId string
        var subsId string

        resp, httpRes, err := apiClient.QueryAMFSubscriptionInfoDocumentApi.GetAmfGroupSubscriptions(context.Background(), ueGroupId, subsId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test QueryAMFSubscriptionInfoDocumentApiService GetAmfSubscriptionInfo", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var ueId string
        var subsId string

        resp, httpRes, err := apiClient.QueryAMFSubscriptionInfoDocumentApi.GetAmfSubscriptionInfo(context.Background(), ueId, subsId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
