/*
Npcf_AMPolicyAuthorization Service API

Testing AMPolicyEventsSubscriptionDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Npcf_AMPolicyAuthorization

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Npcf_AMPolicyAuthorization_AMPolicyEventsSubscriptionDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test AMPolicyEventsSubscriptionDocumentApiService DeleteAmEventsSubsc", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var appAmContextId string

        resp, httpRes, err := apiClient.AMPolicyEventsSubscriptionDocumentApi.DeleteAmEventsSubsc(context.Background(), appAmContextId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test AMPolicyEventsSubscriptionDocumentApiService UpdateAmEventsSubsc", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var appAmContextId string

        resp, httpRes, err := apiClient.AMPolicyEventsSubscriptionDocumentApi.UpdateAmEventsSubsc(context.Background(), appAmContextId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
