/*
Ntsctsf_TimeSynchronization Service API

Testing IndividualTimeSynchronizationExposureSubscriptionDocumentApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Ntsctsf_TimeSynchronization

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Ntsctsf_TimeSynchronization_IndividualTimeSynchronizationExposureSubscriptionDocumentApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualTimeSynchronizationExposureSubscriptionDocumentApiService DeleteIndividualTimeSynchronizationExposureSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualTimeSynchronizationExposureSubscriptionDocumentApi.DeleteIndividualTimeSynchronizationExposureSubscription(context.Background(), subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualTimeSynchronizationExposureSubscriptionDocumentApiService GetIndividualTimeSynchronizationExposureSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualTimeSynchronizationExposureSubscriptionDocumentApi.GetIndividualTimeSynchronizationExposureSubscription(context.Background(), subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualTimeSynchronizationExposureSubscriptionDocumentApiService ReplaceIndividualTimeSynchronizationExposureSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var subscriptionId string

        resp, httpRes, err := apiClient.IndividualTimeSynchronizationExposureSubscriptionDocumentApi.ReplaceIndividualTimeSynchronizationExposureSubscription(context.Background(), subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
