/*
Nhss_EE

HSS Event Exposure.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Nhss_EE

import (
	"encoding/json"
)

// LossConnectivityConfiguration Contains data needed for a Monitoring Configuration, specific to the 'Loss of Connectivity' event type
type LossConnectivityConfiguration struct {
	// indicating a time in seconds.
	MaxDetectionTime *int32 `json:"maxDetectionTime,omitempty"`
}

// NewLossConnectivityConfiguration instantiates a new LossConnectivityConfiguration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLossConnectivityConfiguration() *LossConnectivityConfiguration {
	this := LossConnectivityConfiguration{}
	return &this
}

// NewLossConnectivityConfigurationWithDefaults instantiates a new LossConnectivityConfiguration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLossConnectivityConfigurationWithDefaults() *LossConnectivityConfiguration {
	this := LossConnectivityConfiguration{}
	return &this
}

// GetMaxDetectionTime returns the MaxDetectionTime field value if set, zero value otherwise.
func (o *LossConnectivityConfiguration) GetMaxDetectionTime() int32 {
	if o == nil || isNil(o.MaxDetectionTime) {
		var ret int32
		return ret
	}
	return *o.MaxDetectionTime
}

// GetMaxDetectionTimeOk returns a tuple with the MaxDetectionTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LossConnectivityConfiguration) GetMaxDetectionTimeOk() (*int32, bool) {
	if o == nil || isNil(o.MaxDetectionTime) {
    return nil, false
	}
	return o.MaxDetectionTime, true
}

// HasMaxDetectionTime returns a boolean if a field has been set.
func (o *LossConnectivityConfiguration) HasMaxDetectionTime() bool {
	if o != nil && !isNil(o.MaxDetectionTime) {
		return true
	}

	return false
}

// SetMaxDetectionTime gets a reference to the given int32 and assigns it to the MaxDetectionTime field.
func (o *LossConnectivityConfiguration) SetMaxDetectionTime(v int32) {
	o.MaxDetectionTime = &v
}

func (o LossConnectivityConfiguration) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.MaxDetectionTime) {
		toSerialize["maxDetectionTime"] = o.MaxDetectionTime
	}
	return json.Marshal(toSerialize)
}

type NullableLossConnectivityConfiguration struct {
	value *LossConnectivityConfiguration
	isSet bool
}

func (v NullableLossConnectivityConfiguration) Get() *LossConnectivityConfiguration {
	return v.value
}

func (v *NullableLossConnectivityConfiguration) Set(val *LossConnectivityConfiguration) {
	v.value = val
	v.isSet = true
}

func (v NullableLossConnectivityConfiguration) IsSet() bool {
	return v.isSet
}

func (v *NullableLossConnectivityConfiguration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLossConnectivityConfiguration(val *LossConnectivityConfiguration) *NullableLossConnectivityConfiguration {
	return &NullableLossConnectivityConfiguration{value: val, isSet: true}
}

func (v NullableLossConnectivityConfiguration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLossConnectivityConfiguration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


