/*
Namf_MBSCommunication

AMF Communication Service for MBS.   © 2022, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package Namf_MBSCommunication

import (
	"encoding/json"
)

// MbsN2MessageTransferRspData Data within MBS N2 Message Transfer Response
type MbsN2MessageTransferRspData struct {
	Result N2InformationTransferResult `json:"result"`
	// A string used to indicate the features supported by an API that is used as defined in clause  6.6 in 3GPP TS 29.500. The string shall contain a bitmask indicating supported features in  hexadecimal representation Each character in the string shall take a value of \"0\" to \"9\",  \"a\" to \"f\" or \"A\" to \"F\" and shall represent the support of 4 features as described in  table 5.2.2-3. The most significant character representing the highest-numbered features shall  appear first in the string, and the character representing features 1 to 4 shall appear last  in the string. The list of features and their numbering (starting with 1) are defined  separately for each API. If the string contains a lower number of characters than there are  defined features for an API, all features that would be represented by characters that are not  present in the string are not supported. 
	SupportedFeatures *string `json:"supportedFeatures,omitempty"`
}

// NewMbsN2MessageTransferRspData instantiates a new MbsN2MessageTransferRspData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMbsN2MessageTransferRspData(result N2InformationTransferResult) *MbsN2MessageTransferRspData {
	this := MbsN2MessageTransferRspData{}
	this.Result = result
	return &this
}

// NewMbsN2MessageTransferRspDataWithDefaults instantiates a new MbsN2MessageTransferRspData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMbsN2MessageTransferRspDataWithDefaults() *MbsN2MessageTransferRspData {
	this := MbsN2MessageTransferRspData{}
	return &this
}

// GetResult returns the Result field value
func (o *MbsN2MessageTransferRspData) GetResult() N2InformationTransferResult {
	if o == nil {
		var ret N2InformationTransferResult
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *MbsN2MessageTransferRspData) GetResultOk() (*N2InformationTransferResult, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *MbsN2MessageTransferRspData) SetResult(v N2InformationTransferResult) {
	o.Result = v
}

// GetSupportedFeatures returns the SupportedFeatures field value if set, zero value otherwise.
func (o *MbsN2MessageTransferRspData) GetSupportedFeatures() string {
	if o == nil || isNil(o.SupportedFeatures) {
		var ret string
		return ret
	}
	return *o.SupportedFeatures
}

// GetSupportedFeaturesOk returns a tuple with the SupportedFeatures field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MbsN2MessageTransferRspData) GetSupportedFeaturesOk() (*string, bool) {
	if o == nil || isNil(o.SupportedFeatures) {
    return nil, false
	}
	return o.SupportedFeatures, true
}

// HasSupportedFeatures returns a boolean if a field has been set.
func (o *MbsN2MessageTransferRspData) HasSupportedFeatures() bool {
	if o != nil && !isNil(o.SupportedFeatures) {
		return true
	}

	return false
}

// SetSupportedFeatures gets a reference to the given string and assigns it to the SupportedFeatures field.
func (o *MbsN2MessageTransferRspData) SetSupportedFeatures(v string) {
	o.SupportedFeatures = &v
}

func (o MbsN2MessageTransferRspData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["result"] = o.Result
	}
	if !isNil(o.SupportedFeatures) {
		toSerialize["supportedFeatures"] = o.SupportedFeatures
	}
	return json.Marshal(toSerialize)
}

type NullableMbsN2MessageTransferRspData struct {
	value *MbsN2MessageTransferRspData
	isSet bool
}

func (v NullableMbsN2MessageTransferRspData) Get() *MbsN2MessageTransferRspData {
	return v.value
}

func (v *NullableMbsN2MessageTransferRspData) Set(val *MbsN2MessageTransferRspData) {
	v.value = val
	v.isSet = true
}

func (v NullableMbsN2MessageTransferRspData) IsSet() bool {
	return v.isSet
}

func (v *NullableMbsN2MessageTransferRspData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMbsN2MessageTransferRspData(val *MbsN2MessageTransferRspData) *NullableMbsN2MessageTransferRspData {
	return &NullableMbsN2MessageTransferRspData{value: val, isSet: true}
}

func (v NullableMbsN2MessageTransferRspData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMbsN2MessageTransferRspData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


