/*
Nhss_EE

Testing UpdateEESubscriptionApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package Nhss_EE

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_Nhss_EE_UpdateEESubscriptionApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test UpdateEESubscriptionApiService UpdateEeSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var ueId string
        var subscriptionId string

        resp, httpRes, err := apiClient.UpdateEESubscriptionApi.UpdateEeSubscription(context.Background(), ueId, subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
