/*
3gpp-monitoring-event

Testing MonitoringEventSubscriptionsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package MonitoringEvent

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_MonitoringEvent_MonitoringEventSubscriptionsApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test MonitoringEventSubscriptionsApiService CreateMonitoringEventSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var scsAsId string

        resp, httpRes, err := apiClient.MonitoringEventSubscriptionsApi.CreateMonitoringEventSubscription(context.Background(), scsAsId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test MonitoringEventSubscriptionsApiService FetchAllMonitoringEventSubscriptions", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var scsAsId string

        resp, httpRes, err := apiClient.MonitoringEventSubscriptionsApi.FetchAllMonitoringEventSubscriptions(context.Background(), scsAsId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
