/*
VAE_PC5ProvisioningRequirement

Testing VAEPC5ProvisioningRequirementSubscriptionResourcePutServiceOperationApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package VAE_PC5ProvisioningRequirement

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_VAE_PC5ProvisioningRequirement_VAEPC5ProvisioningRequirementSubscriptionResourcePutServiceOperationApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test VAEPC5ProvisioningRequirementSubscriptionResourcePutServiceOperationApiService UpdatePC5ProvisioningRequirementSubscription", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var subscriptionId string

        resp, httpRes, err := apiClient.VAEPC5ProvisioningRequirementSubscriptionResourcePutServiceOperationApi.UpdatePC5ProvisioningRequirementSubscription(context.Background(), subscriptionId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
