/*
3gpp-ecs-address-provision

Testing IndividualECSAddressProvisionConfigurationApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package EcsAddressProvision

import (
    "context"
    "github.com/stretchr/testify/assert"
    "github.com/stretchr/testify/require"
    "testing"
    openapiclient "./openapi"
)

func Test_EcsAddressProvision_IndividualECSAddressProvisionConfigurationApiService(t *testing.T) {

    configuration := openapiclient.NewConfiguration()
    apiClient := openapiclient.NewAPIClient(configuration)

    t.Run("Test IndividualECSAddressProvisionConfigurationApiService DeleteAnConfiguration", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var afId string
        var configurationId string

        resp, httpRes, err := apiClient.IndividualECSAddressProvisionConfigurationApi.DeleteAnConfiguration(context.Background(), afId, configurationId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualECSAddressProvisionConfigurationApiService FullyUpdateAnConfiguration", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var afId string
        var configurationId string

        resp, httpRes, err := apiClient.IndividualECSAddressProvisionConfigurationApi.FullyUpdateAnConfiguration(context.Background(), afId, configurationId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

    t.Run("Test IndividualECSAddressProvisionConfigurationApiService ReadAnConfiguration", func(t *testing.T) {

        t.Skip("skip test")  // remove to run test

        var afId string
        var configurationId string

        resp, httpRes, err := apiClient.IndividualECSAddressProvisionConfigurationApi.ReadAnConfiguration(context.Background(), afId, configurationId).Execute()

        require.Nil(t, err)
        require.NotNil(t, resp)
        assert.Equal(t, 200, httpRes.StatusCode)

    })

}
